@startuml
participant Geezer as g
actor ONE as g1
actor TWO as g2
actor THREE as g3
actor FOUR as g4
actor FIVE as g5
actor SIX as g6
actor SEVEN as g7
entity Line as l
entity BubbleSorter as s

l->l:创建
g1->g1:创建
l->g1:置于6号位
g2->g2:创建
l->g2:置于3号位
g3->g3:创建
l->g3:置于1号位
g4->g4:创建
l->g4:置于5号位
g5->g5:创建
l->g5:置于2号位
g6->g6:创建
l->g6:置于4号位
g7->g7:创建
l->g7:置于0号位
g->g:创建
s->s:创建
g->s:装载
g->s:使用冒泡排序算法对葫芦娃进行排序
==冒泡排序过程（由于过程冗长，此处略过）==

@enduml